nguage: r
dist: trusty
sudo: false

branches:
  only:
    - master
    - dev

cache:
  packages: yes
  directories:
    - $HOME/bin

before_script:
  - "R -e 'blogdown::install_hugo()'"

script:
  - "R -e 'blogdown::build_site()'"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  local_dir: public
  fqdn: pedramnavid.me
