baseurl = "/"
languageCode = "en-us"
theme = "terminal"
paginate = 5
summaryLength = 100

[params]
  contentTypeName = "posts"
  themeColor = "green"
  showMenuItems = 2
  showLanguageSelector = false
  fullWidthTheme = false
  centerTheme = false
  # favicon = "favicon.ico"

[params.twitter]
  # set Twitter handles for Twitter cards
  # see https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started#card-and-content-attribution
  # do not include @
  creator = "pedram__navid"
  site = ""

[languages]
  [languages.en]
    languageName = "English"
    title = "pedramnavid.me"
    subtitle = "adventures in data and code"
    owner = ""
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Terminal"
      logoHomeLink = "/"
